### ISSUE TITLE
pattern.Pattern requires its interfaces to have same number of levels

### ISSUE THREAD

**Issue by chungheng** [neurokernel/neurokernel#37] opened 2015-01-30 22:15 UTC
In revision 6fb5317ad7d94de85348b585b8c68ac93fe62c1c, in the sensory integration example, the vision LPUs have port selectors with 3 levels, while the olfaction LPU has port selectors with 4 levels. Thus, when the integration LPU is set up with selectors of either 3 levels or 4 level, it will only be compatible with one sensory LPU, namely, either the medulla or the antennal lobe but not both.

**Comment by chungheng** [comment] 2015-01-30 22:16
A tentative solution would be to setup every LPU (lam, med, al, and int) with selectors of 3 levels.

**Comment by lebedov** [comment] 2015-02-01 20:39
Duplicate of #27.

**Closed by lebedov** 2015-02-01 20:39 UTC
Labels: bug, duplicate
